=== Queueing-Systems-Assistance/qsa-system-config-pack/qsa-config-pack-assembler/src/test/resources/config-schema.json
{
	"$id": "http://qsa.inf.unideb.hu/qsa-schema.json",
	"$schema": "http://json-schema.org/draft-07/schema#",
	"definitions": {
		"primitiveType": {
			"type": [
				"boolean",
				"number",
				"array",
				"string",
				"object"
			]
		},
		"configNameType": {
			"type": "string",
			"pattern": "^([0-9A-Za-z_.]*)$",
			"minLength": 3,
			"maxLength": 100
		},
		"qualifiersAsValues": {
			"type": "string",
			"minItems": 1,
			"pattern": "^([0-9A-Za-z_\\-]*)$",
			"examples": [
				"locale",
				"environment"
			]
		},
		"configCondition": {
			"type": "array",
			"minItems": 1,
			"items": {
				"$ref": "#/definitions/qualifiersAsValues"
			}
		},
		"values": {
			"type": "array",
			"minItems": 1,
			"items": {
				"properties": {
					"value": {
						"description": "The value of the config in the scenario.",
						"$ref": "#/definitions/primitiveType"
					}
				},
				"patternProperties": {
					"^(?!value$)([0-9a-zA-Z\\-_]*)$": {
						"description": "Qualifier for the given value. If the user context matches a value from each qualifier, the given config value is resolved.",
						"type": "array",
						"minItems": 1,
						"items": {
							"$ref": "#/definitions/primitiveType"
						}
					}
				},
				"additionalProperties": false,
				"required": [
					"value"
				]
			}
		}
	},
	"properties": {
		"config": {
			"description": "Name of the config being defined. Must be same as the file name.",
			"$ref": "#/definitions/configNameType"
		},
		"name": {
			"description": "Name of the config.",
			"type": "string"
		},
		"configCondition": {
			"description": "Defines the priority of config values. See examples in the doc.",
			"$ref": "#/definitions/configCondition"
		},
		"values": {
			"description": "Scenarios defining the possible values that the config can take. At least one scenario should be declared which gives the default value of the config.",
			"$ref": "#/definitions/values"
		},
		"description": {
			"description": "Short description of the config.",
			"type": "string"
		}
	},
	"required": [
		"config",
		"values"
	],
	"additionalProperties": false
}

=== Queueing-Systems-Assistance/qsa-system-config-pack/qsa-config-pack-assembler/src/main/resources/config/systemMM2/VALIDATOR_CONSTRAINTS.json
{
  "config": "VALIDATOR_CONSTRAINTS",
  "name": "systemMM2",
  "configCondition": [
    "feature"
  ],
  "values": [
    {
      "feature": [
        "r",
        "t",
        "n",
        "CS",
        "CWS",
        "CI",
        "CSR",
        "R"
      ],
      "value": "positiveOrZeroValidator"
    },
    {
      "feature": [
        "Lambda",
        "Mu"
      ],
      "value": "positiveValidator"
    }
  ]
}

=== Queueing-Systems-Assistance/qsa-system-config-pack/src/main/resources/config/systemMMn/CALCULATION_INPUT_VALIDATOR.json
{
	"config": "CALCULATION_INPUT_VALIDATOR",
	"name": "systemMMn",
	"configCondition": [
        "feature",
        "output"
	],
	"values": [
        {
            "value": "positiveValidator",
            "output": [
                "WAvgW"
            ],
            "feature": [
                "t"
            ]
        }
	]
}

=== Queueing-Systems-Assistance/qsa-system-config-pack/src/main/resources/config/systemMErlang1KK/INPUT_GROUPS.json
{
  "config": "INPUT_GROUPS",
  "name": "systemMErlang1KK",
  "configCondition": [
    "feature"
  ],
  "values": [
    {
      "value": "INPUT_GROUP_REQUIRED",
      "feature": [
        "LambdaFin",
        "nErlang",
        "Mu",
        "KFin"
      ]
    },
    {
      "value": "INPUT_GROUP_OPTIONAL"
    }
  ]
}

=== Queueing-Systems-Assistance/qsa-system-config-pack/src/main/resources/config/systemMMcKReneging/VALIDATOR_CONSTRAINTS.json
{
  "config": "VALIDATOR_CONSTRAINTS",
  "name": "systemMMcKReneging",
  "configCondition": [
    "feature"
  ],
  "values": [
    {
      "feature": [
        "n"
      ],
      "value": "positiveOrZeroValidator"
    },
    {
      "feature": [
        "Lambda",
        "Mu",
        "c",
        "K",
        "Theta"
      ],
      "value": "positiveValidator"
    }
  ]
}

=== Queueing-Systems-Assistance/qsa-system-config-pack/src/main/resources/config/systemMHyper1KK2/VALIDATOR_CONSTRAINTS.json
{
  "config": "VALIDATOR_CONSTRAINTS",
  "name": "systemMHyper1KK2",
  "configCondition": [
    "feature"
  ],
  "values": [
    {
      "feature": [
        "LambdaFin",
        "Mu1",
        "Mu2",
        "p1",
        "p2",
        "KFin"
      ],
      "value": "positiveValidator"
    },
    {
        "feature": [
            "n"
        ],
        "value": "positiveOrZeroValidator"
    }
  ]
}

=== Queueing-Systems-Assistance/qsa-system-config-pack/src/main/resources/config/systemMMnPrior/ADDITIONAL_INFORMATION.json
{
  "config": "ADDITIONAL_INFORMATION",
  "name": "systemMMnPrior",
  "configCondition": [
    "locale"
  ],
  "values": [
    {
      "value": [
        "Poisson-folyamat, c szerver",
        "Exponenciális eloszlású beérkezési időközök",
        "Exponenciális eloszlású kiszolgálási időközök",
        "Az egyes típusú igény érkezésekor a kettes típusú igény kiszolgálása nem szakad meg, de a kiszolgálás befejeződésekor az egyes típusúak kiszolgálása kezdődik"
      ],
      "locale": [
        "hu"
      ]
    },
    {
      "value": [
        "Poisson process, c servers",
        "Exponentially distributed arrival times",
        "Exponentially distributed service times",
        "Class 1 customer does not interrupt the service of class 2 request",
        "Sometimes this discipline is called HOL ( Head Of the Line )"
      ]
    }
  ]
}

=== Queueing-Systems-Assistance/qsa-system-config-pack/src/main/resources/config/systemMMcmKReneging/VALIDATOR_CONSTRAINTS.json
{
  "config": "VALIDATOR_CONSTRAINTS",
  "name": "systemMMcmKReneging",
  "configCondition": [
    "feature"
  ],
  "values": [
    {
      "feature": [
        "n"
      ],
      "value": "positiveOrZeroValidator"
    },
    {
      "feature": [
        "Lambda",
        "Mu",
        "c",
        "m",
        "K",
        "Theta"
      ],
      "value": "positiveValidator"
    }
  ]
}

=== Queueing-Systems-Assistance/qsa-system-config-pack/src/main/resources/config/systemMHyper1KK2/INPUT_GROUPS.json
{
  "config": "INPUT_GROUPS",
  "name": "systemMHyper1KK2",
  "configCondition": [
    "feature"
  ],
  "values": [
    {
      "value": "INPUT_GROUP_REQUIRED",
      "feature": [
        "LambdaFin",
        "Mu1",
        "Mu2",
        "p1",
        "p2",
        "KFin"
      ]
    },
    {
      "value": "INPUT_GROUP_COST",
      "feature": [
        "CS",
        "CWS",
        "CI",
        "CSR",
        "R"
      ]
    }
  ]
}
