=== Queueing-Systems-Assistance/qsa-system-config-pack/qsa-config-pack-assembler/src/test/resources/config-schema.json
{
	"$id": "http://qsa.inf.unideb.hu/qsa-schema.json",
	"$schema": "http://json-schema.org/draft-07/schema#",
	"definitions": {
		"primitiveType": {
			"type": [
				"boolean",
				"number",
				"array",
				"string",
				"object"
			]
		},
		"configNameType": {
			"type": "string",
			"pattern": "^([0-9A-Za-z_.]*)$",
			"minLength": 3,
			"maxLength": 100
		},
		"qualifiersAsValues": {
			"type": "string",
			"minItems": 1,
			"pattern": "^([0-9A-Za-z_\\-]*)$",
			"examples": [
				"locale",
				"environment"
			]
		},
		"configCondition": {
			"type": "array",
			"minItems": 1,
			"items": {
				"$ref": "#/definitions/qualifiersAsValues"
			}
		},
		"values": {
			"type": "array",
			"minItems": 1,
			"items": {
				"properties": {
					"value": {
						"description": "The value of the config in the scenario.",
						"$ref": "#/definitions/primitiveType"
					}
				},
				"patternProperties": {
					"^(?!value$)([0-9a-zA-Z\\-_]*)$": {
						"description": "Qualifier for the given value. If the user context matches a value from each qualifier, the given config value is resolved.",
						"type": "array",
						"minItems": 1,
						"items": {
							"$ref": "#/definitions/primitiveType"
						}
					}
				},
				"additionalProperties": false,
				"required": [
					"value"
				]
			}
		}
	},
	"properties": {
		"config": {
			"description": "Name of the config being defined. Must be same as the file name.",
			"$ref": "#/definitions/configNameType"
		},
		"name": {
			"description": "Name of the config.",
			"type": "string"
		},
		"configCondition": {
			"description": "Defines the priority of config values. See examples in the doc.",
			"$ref": "#/definitions/configCondition"
		},
		"values": {
			"description": "Scenarios defining the possible values that the config can take. At least one scenario should be declared which gives the default value of the config.",
			"$ref": "#/definitions/values"
		},
		"description": {
			"description": "Short description of the config.",
			"type": "string"
		}
	},
	"required": [
		"config",
		"values"
	],
	"additionalProperties": false
}

=== Queueing-Systems-Assistance/qsa-system-config-pack/src/main/resources/config/systemMMnK/ADDITIONAL_INFORMATION.json
{
	"config": "ADDITIONAL_INFORMATION",
	"name": "systemMMnK",
	"configCondition": [
		"locale"
	],
	"values": [
		{
			"value": "Poisson-folyamat<br>Exponenciális eloszlású beérkezési időközök<br>Exponenciális eloszlású kiszolgálási időközök<br><b>c</b> kiszolgáló<br>Maximálisan <b>K</b> igény tartózkodhat a rendszerben",
			"locale": [
				"hu"
			]
		},
		{
			"value": "Poisson process<br>Exponentially distributed arrival times<br>Exponentially distributed service times<br><b>c</b> servers<br>System capacity is <b>K</b>"
		}
	]
}

=== Queueing-Systems-Assistance/qsa-system-config-pack/src/main/resources/config/systemMMcmKBalkingReneging/INPUT_GROUPS.json
{
  "config": "INPUT_GROUPS",
  "name": "systemMMcmKBalkingReneging",
  "configCondition": [
    "feature"
  ],
  "values": [
    {
      "value": "INPUT_GROUP_REQUIRED",
      "feature": [
        "LambdaFin",
        "Mu",
        "c",
        "m",
        "KFin",
        "Theta"
      ]
    }
  ]
}

=== Queueing-Systems-Assistance/qsa-system-config-pack/src/main/resources/config/systemMM2/CALCULATION_INPUT_VALIDATOR.json
{
	"config": "CALCULATION_INPUT_VALIDATOR",
	"name": "systemMM2",
	"configCondition": [
        "feature",
        "output"
	],
	"values": [
		{
            "value": "positiveValidator",
            "output": [
                "Pn"
            ],
            "feature": [
                "n"
            ]
        },
        {
            "value": "positiveValidator",
            "output": [
                "WAvgW"
            ],
            "feature": [
                "t"
            ]
        }
	]
}

=== Queueing-Systems-Assistance/qsa-system-config-pack/src/main/resources/config/systemMM1Balking/ADDITIONAL_INFORMATION.json
{
	"config": "ADDITIONAL_INFORMATION",
	"name": "systemMM1Balking",
	"configCondition": [
		"locale"
	],
	"values": [
		{
			"value": "Poisson-folyamat<br>Exponenciális eloszlású beérkezési időközök<br>Exponenciális eloszlású kiszolgálási időközök<br><b>1</b> kiszolgáló<br>A rendszerhez az érkező igények a nagyobb sorhossz láttán egyre kisebb valószínűséggel csatlakoznak",
			"locale": [
				"hu"
			]
		},
		{
			"value": "Poisson process<br>Exponentially distributed arrival times<br>Exponentially distributed service times<br><b>1</b> server<br>Customers are discouraged, when more and more requests are present at their arrivals"
		}
	]
}

=== Queueing-Systems-Assistance/qsa-system-config-pack/src/main/resources/config/systemMM1Preemp/ADDITIONAL_INFORMATION.json
{
	"config": "ADDITIONAL_INFORMATION",
	"name": "systemMM1Preemp",
	"configCondition": [
		"locale"
	],
	"values": [
		{
			"value": "Poisson-folyamat<br>Exponenciális eloszlású beérkezési időközök<br>Exponenciális eloszlású kiszolgálási időközök<br>Ha egy kettes típusú igény kiszolgálás alatt áll és egy egyes típusú érkezik, akkor a kettes típusú kiszolgálása megszakításra kerül és az egyes típusú kiszolgálása következik",
			"locale": [
				"hu"
			]
		},
		{
			"value": "Poisson process<br>Exponentially distributed arrival times<br>Exponentially distributed service times<br>If a class 2 customer is under service when a class 1 request arrives the service stops and the service of class 1 request starts"
		}
	]
}

=== Queueing-Systems-Assistance/qsa-system-config-pack/src/main/resources/config/systemMMn/INPUT_GROUPS.json
{
  "config": "INPUT_GROUPS",
  "name": "systemMMn",
  "configCondition": [
    "feature"
  ],
  "values": [
    {
      "value": "INPUT_GROUP_REQUIRED",
      "feature": [
        "Mu",
        "Lambda",
        "c"
      ]
    },
    {
      "value": "INPUT_GROUP_COST",
      "feature": [
        "CS",
        "CWS",
        "CI",
        "CSR",
        "R"
      ]
    }
  ]
}

=== Queueing-Systems-Assistance/qsa-system-config-pack/src/main/resources/config/systemMM1Preemp/INPUT_GROUPS.json
{
  "config": "INPUT_GROUPS",
  "name": "systemMM1Preemp",
  "configCondition": [
    "feature"
  ],
  "values": [
    {
      "value": "INPUT_GROUP_REQUIRED",
      "feature": [
        "Lambda1",
        "Lambda2",
        "Mu"
      ]
    },
    {
      "value": "INPUT_GROUP_COST",
      "feature": [
        "CS",
        "CWS",
        "CI",
        "CSR",
        "R"
      ]
    }
  ]
}

=== Queueing-Systems-Assistance/qsa-system-config-pack/src/main/resources/config/systemDDnKK/ADDITIONAL_INFORMATION.json
{
  "config": "ADDITIONAL_INFORMATION",
  "name": "systemDDnKK",
  "configCondition": [
    "locale"
  ],
  "values": [
    {
      "value": [
        "Konstans érkezési időközök",
        "Konstans kiszolgálási időközök",
        "<b>c</b> kiszolgáló",
        "Maximálisan <b>K</b> igény tartózkodhat a rendszerben",
        "<b>K</b> igényforrás"
      ],
      "locale": [
        "hu"
      ]
    },
    {
      "value": [
        "Deterministic arrival times",
        "Deterministic service times",
        "<b>c</b> servers",
        "System capacity is <b>K</b>",
        "<b>K</b> sources of customers"
      ]
    }
  ]
}
