=== Queueing-Systems-Assistance/qsa-system-config-pack/qsa-config-pack-assembler/src/test/resources/config-schema.json
{
	"$id": "http://qsa.inf.unideb.hu/qsa-schema.json",
	"$schema": "http://json-schema.org/draft-07/schema#",
	"definitions": {
		"primitiveType": {
			"type": [
				"boolean",
				"number",
				"array",
				"string",
				"object"
			]
		},
		"configNameType": {
			"type": "string",
			"pattern": "^([0-9A-Za-z_.]*)$",
			"minLength": 3,
			"maxLength": 100
		},
		"qualifiersAsValues": {
			"type": "string",
			"minItems": 1,
			"pattern": "^([0-9A-Za-z_\\-]*)$",
			"examples": [
				"locale",
				"environment"
			]
		},
		"configCondition": {
			"type": "array",
			"minItems": 1,
			"items": {
				"$ref": "#/definitions/qualifiersAsValues"
			}
		},
		"values": {
			"type": "array",
			"minItems": 1,
			"items": {
				"properties": {
					"value": {
						"description": "The value of the config in the scenario.",
						"$ref": "#/definitions/primitiveType"
					}
				},
				"patternProperties": {
					"^(?!value$)([0-9a-zA-Z\\-_]*)$": {
						"description": "Qualifier for the given value. If the user context matches a value from each qualifier, the given config value is resolved.",
						"type": "array",
						"minItems": 1,
						"items": {
							"$ref": "#/definitions/primitiveType"
						}
					}
				},
				"additionalProperties": false,
				"required": [
					"value"
				]
			}
		}
	},
	"properties": {
		"config": {
			"description": "Name of the config being defined. Must be same as the file name.",
			"$ref": "#/definitions/configNameType"
		},
		"name": {
			"description": "Name of the config.",
			"type": "string"
		},
		"configCondition": {
			"description": "Defines the priority of config values. See examples in the doc.",
			"$ref": "#/definitions/configCondition"
		},
		"values": {
			"description": "Scenarios defining the possible values that the config can take. At least one scenario should be declared which gives the default value of the config.",
			"$ref": "#/definitions/values"
		},
		"description": {
			"description": "Short description of the config.",
			"type": "string"
		}
	},
	"required": [
		"config",
		"values"
	],
	"additionalProperties": false
}

=== Queueing-Systems-Assistance/qsa-system-config-pack/src/main/resources/config/systemMGamma1/ADDITIONAL_INFORMATION.json
{
	"config": "ADDITIONAL_INFORMATION",
	"name": "systemMGamma1",
	"configCondition": [
		"locale"
	],
	"values": [
		{
			"value": "<b>1</b> kiszolgáló, Poisson beérkezés<br>Gamma eloszlású kiszolgálási időközök<br>Beérkezési intenzitás <b>λ</b><br>Kiszolgálási intenzitás <b>µ</b>",
			"locale": [
				"hu"
			]
		},
		{
			"value": "Single-server queue with Poisson arrivals<br>Gamma distributed service times<br>Arrival rate is <b>λ</b><br>Service rate is <b>µ</b>"
		}
	]
}

=== Queueing-Systems-Assistance/qsa-system-config-pack/qsa-config-pack-assembler/src/main/resources/config/systemMM1K/CALCULATION_INPUT_VALIDATOR.json
{
  "config": "CALCULATION_INPUT_VALIDATOR",
  "name": "systemMM1K",
  "configCondition": [
    "feature"
  ],
  "values": [
    {
      "value": "smallerEqualsnFromKValidator",
      "feature": [
        "Pn",
        "n"
      ]
    },
    {
      "value": "smallernFromKValidator",
      "feature": [
        "Pin",
        "n"
      ]
    }
  ]
}

=== Queueing-Systems-Assistance/qsa-system-config-pack/src/main/resources/config/systemMMnn/CALCULATION_INPUT_VALIDATOR.json
{
	"config": "CALCULATION_INPUT_VALIDATOR",
	"name": "systemMMnn",
	"configCondition": [
        "feature",
        "output"
	],
	"values": [
        {
            "value": "positiveValidator",
            "output": [
                "US"
            ],
            "feature": [
                "n"
            ]
        }
	]
}

=== Queueing-Systems-Assistance/qsa-system-config-pack/src/main/resources/config/systemMMcKBalking/VALIDATOR_CONSTRAINTS.json
{
  "config": "VALIDATOR_CONSTRAINTS",
  "name": "systemMMcKBalking",
  "configCondition": [
    "feature"
  ],
  "values": [
    {
      "feature": [
        "n"
      ],
      "value": "positiveOrZeroValidator"
    },
    {
      "feature": [
        "Lambda",
        "Mu",
        "c",
        "K"
      ],
      "value": "positiveValidator"
    }
  ]
}

=== Queueing-Systems-Assistance/qsa-system-config-pack/src/main/resources/config/systemMMcmK/INPUT_GROUPS.json
{
  "config": "INPUT_GROUPS",
  "name": "systemMMcmK",
  "configCondition": [
    "feature"
  ],
  "values": [
    {
      "value": "INPUT_GROUP_REQUIRED",
      "feature": [
        "LambdaFin",
        "Mu",
        "c",
        "m",
        "KFin"
      ]
    },
    {
      "value": "INPUT_GROUP_OPTIONAL"
    }
  ]
}

=== Queueing-Systems-Assistance/qsa-system-config-pack/src/main/resources/config/systemMMnPrior/INPUT_GROUPS.json
{
  "config": "INPUT_GROUPS",
  "name": "systemMMnPrior",
  "configCondition": [
    "feature"
  ],
  "values": [
    {
      "value": "INPUT_GROUP_REQUIRED",
      "feature": [
        "Lambda1",
        "Lambda2",
        "Mu",
        "c"
      ]
    },
    {
      "value": "INPUT_GROUP_COST",
      "feature": [
        "CS",
        "CWS",
        "CI",
        "CSR",
        "R"
      ]
    }
  ]
}

=== Queueing-Systems-Assistance/qsa-system-config-pack/qsa-config-pack-assembler/src/main/resources/config/systemMMn/VALIDATOR_CONSTRAINTS.json
{
  "config": "VALIDATOR_CONSTRAINTS",
  "name": "systemMMn",
  "configCondition": [
    "feature"
  ],
  "values": [
    {
      "feature": [
        "n",
        "t",
        "r",
        "CS",
        "CWS",
        "CI",
        "CSR",
        "R"
      ],
      "value": "positiveOrZeroValidator"
    },
    {
      "feature": [
        "Lambda",
        "Mu",
        "c"
      ],
      "value": "positiveValidator"
    }
  ]
}

=== Queueing-Systems-Assistance/qsa-system-config-pack/src/main/resources/config/systemMM1K/VALIDATOR_CONSTRAINTS.json
{
	"config": "VALIDATOR_CONSTRAINTS",
	"name": "systemMM1K",
	"configCondition": [
		"feature"
	],
	"values": [
		{
			"feature": [
				"n",
				"t",
				"r"
			],
			"value": "positiveOrZeroValidator"
		},
		{
			"feature": [
				"Lambda",
				"Mu",
				"K"
			],
			"value": "positiveValidator"
		}
	]
}
